# Generated by Django 4.2.11 on 2024-05-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travelPros", "0002_traveler_arrival_city_traveler_departure_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="traveler", old_name="arrival_date", new_name="return_date",
        ),
    ]
